### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by Nekkok** [constellation-mc/Linkart#1]
I'm utterly confused. Why isn't this mod still updated? Looks fantastic btw.

**Comment by zenfyrdev** [comment]
Hi, I personally don't really see a reason to update this mod to 1.18.2 since Cammie's Minecart tweaks is already doing everything this mod does, but marginally better. 

https://www.curseforge.com/minecraft/mc-mods/cammies-minecart-tweaks

Thanks for asking anyway
