### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KadenMikey00** [constellation-mc/Linkart#11]
**Describe the bug**
Partly a bug but partly a feature request. I'm using the mod High Speed Rail and it seems like once the carts get up to a high speed they lose the connection and break

**To Reproduce**
1. Download High Speed Rail, edit the config so the block of your choice produces the fastest minecart velocity. Then link 2 or more minecarts together and begin traveling at full speed (est 76 blocks per second) The minecarts seem to drift considerably.

**Expected behavior**
I expected the minecarts to have a strong link and not generate distance between one another

**Environment:**
 - Minecraft Version [1.20.1]
 - Mod Version [Fabric] 5.1.1
 - 
I am willing to pay to have this issue patched

**Comment by HatTrkPatrk** [comment]
I'm also having this issue 1.20.2

**Comment by zenfyrdev** [comment]
I'll try to take a look at this on the weekend.

**Comment by vlad8599** [comment]
Still no progress with speed and delink bug?

**Comment by zenfyrdev** [comment]
No

**Comment by zenfyrdev** [comment]
I've cherry-picked a fix from [GeeTransit's fork](https://github.com/GeeTransit/Linkart/tree/audaki-compat), so 5.4.1 should have this fixed.
