### ISSUE TITLE
Forge and Optifine compatibility

### ISSUE THREAD

**Issue by traincrisis** [constellation-mc/Linkart#12]
**Is your feature request related to a problem? Please describe.**
I want to use this mod with Minecraft Reimagined resourcepack

**Describe the solution you'd like**
Make version of this mod for forge 1.18.2 compatible with OptiFIne

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by zenfyrdev** [comment]
Sorry, but I have no plans for a Forge version.
