### ISSUE TITLE
[Bug] Incompatible with Audaki Cart Engine

### ISSUE THREAD

**Issue by Cm4nXD** [constellation-mc/Linkart#21]
**Describe the bug**
Carts disconnect when the first cart in the chain moves too fast.

**To Reproduce**
Install both mods.
https://modrinth.com/mod/audaki-cart-engine
place down powered rails
link a couple of carts
ride in one of them
notice chain breaks

**Expected behavior**
all carts should accelerate with same speed as the first cart and not disconnect.

**Screenshots**
N/A

**Logs**
N/A

**Environment:**
 - Minecraft Version 1.20.1
 - Mod Version Fabric

**Additional context**
N/A

**Comment by zenfyrdev** [comment]
Audaki Cart Engine replaces vanilla minecart logic with its own. I need a hook on Audaki's side, so it falls back to vanilla logic, but the PR implementing this has been rejected. https://github.com/audaki/minecraft-cart-engine/pull/23
