### ISSUE TITLE
[Bug]:Problem with chains drop 

### ISSUE THREAD

**Issue by vlad8599** [constellation-mc/Linkart#24]
**Describe the bug**

**To Reproduce**
1. Start playing and make your first minecart("head") to de-link from others, now remove some other minecarts, that is located in middle of train.
2. You will see that first minecart, "head", moving and chain was dropped. But after removing other minecarts chains wont drop.

**Expected behavior**
Chain drops when any minecart is removed from train.

**Environment:**
 - Minecraft 1.20.4. 
 - Mod Version 5.3.0.

**Comment by zenfyrdev** [comment]
Should be fixed in 5.4.0
