### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by kazikus98** [constellation-mc/Linkart#26]
Hi,
how do I change the configuration file to enable chunkloading? I've tried to approach this from every angle but, I'm not familiar with the technical side of modding.

**Comment by MikeOnDeck** [comment]
Hi @kazikus98. You can actually enable this option by editing the json file that gets generated from the mod after the first run of the game. You can just open the file called linkart.json. It'll be inside the "config" folder in your Minecraft directory (the same directory that contains the "mods" directory). You can open this file in a text editor like Notepad.

```
{
  "pathfindingDistance": 6,
  "velocityMultiplier": 1.0,
  "collisionDepth": 8,
  "distance": 1.2,
  "chunkloading": false,
  "chunkloadingRadius": 3
}
```
You'll see something like this above. Just change the "false" next to "chunkloading" to **true**, and it'll enable chunk loading next time you boot the game.

You can even change the config while the game is running if you don't want to restart. After following the steps above, you can open the console in Minecraft (press T), and type `/linkart config reload` it'll re-load those settings so you can continue on with chunk loading.

**Comment by kazikus98** [comment]
Thank you very much, everything works :) Turns out I was trying to change the settings in a completely different file than needed
