### ISSUE TITLE
[Bug]: problem with de-linking minecarts on high speed while using mod Fabrication

### ISSUE THREAD

**Issue by vlad8599** [constellation-mc/Linkart#28]
### What happened?

(https://www.curseforge.com/minecraft/mc-mods/fabrication) Here is a link to this mod. And now here is a problem.

This bug with de-linking on high speed should be fixed, as you said in previous versions, but its not. Of course I disabled high speed option in that mod, but still. I was chatting in Discord with authors and peoples said, that mod just changes speed on rails and how fast minecart with furnace will consume fuel, logic or physic of minecarts wasnt changed. Can you take a look at this error, please?

### Screenshots

![image](https://github.com/constellation-mc/Linkart/assets/45435607/d346b800-5691-41f3-8585-2703c28f99f8)
![image](https://github.com/constellation-mc/Linkart/assets/45435607/634b16d3-c3f7-4dfc-8d24-580dac93596d)

### Mod Version

5.4.2

### Minecraft Version

1.20.4

**Comment by zenfyrdev** [comment]
I actually tried to patch Audaki with a MASSIVE hack, but thought it was broken because my patcher was wack, but I'm starting to suspect there's something else at play. I'll see what I can do.

**Comment by zenfyrdev** [comment]
> just changes speed on rails

It changes the max speed of furnace minecarts, but the max speed of cart's children remains the same. 

try this build https://github.com/constellation-mc/Linkart/actions/runs/8284340389

**Comment by vlad8599** [comment]
Almost perfect! No more de-link, but now I have this - invisible minecarts models.
![2024-03-15_00 24 58](https://github.com/constellation-mc/Linkart/assets/45435607/354baed8-049b-4557-a892-e2b07508feda)

1.20.4.

**Comment by zenfyrdev** [comment]
Are you sure this has something to do with linkart? The mod is entirely server-side and shouldn't affect rendering.

**Comment by vlad8599** [comment]
Sorry, it was problem with resourcepack. Everything is fine now. Include this fix to new version, please, its perfect!

**Comment by zenfyrdev** [comment]
Fixed in 5.4.3
