### ISSUE TITLE
[Crash]: crash with sinytra connector for all 1.20.1 versions

### ISSUE THREAD

**Issue by HawKDesigns** [constellation-mc/Linkart#29]
### What happened?

It crashes upon start using sinytra connector now on any version of the mod, gives error code 1, shows incompatible modloader in curseforge.

### Logs

https://gist.github.com/HawKDesigns/48d9d29cd467ca104a57e5528e4ddbd1

### Mod Version

any for 1.20.1

### Minecraft Version

1.20.1 forge 47.2.20with latest sinytra connector

**Comment by zenfyrdev** [comment]
Your log has no crash, but either way, issues with Connector should be reported to Connector.

**Comment by zenfyrdev** [comment]
Fixed on Connector's side!
