### ISSUE TITLE
[Crash]: Crash after updating to 5.4.4

### ISSUE THREAD

**Issue by vico93** [constellation-mc/Linkart#31]
### What happened?

I got the following crash after updating Linkart to 5.4.4:

### Logs

https://gist.github.com/vico93/12a7ddf48eeede31e691b9102bbbaad9

### Mod Version

5.4.4

### Minecraft Version

1.20.4

**Comment by zenfyrdev** [comment]
Update [RBIP](https://modrinth.com/mod/rbip/version/0.11.1-1.20.4-build.191).
