### ISSUE TITLE
Crash when going to pause menu on 1.20.6-rc.1

### ISSUE THREAD

**Issue by vico93** [constellation-mc/Linkart#32]
### What happened?

I know Linkart isn't still officially available for 1.20.5 or 1.20.6(-rc.1), but i tried my luck to see if the mod would be still forward-compatible like it was until 1.20.4, and doing this issue more to try to help you in finding the points that need to be addressed in a 1.20.5/6 update, no pressure.

### Logs

https://gist.github.com/vico93/d4ced62c528d4b5d2b92468d21427b0a

### Version

5.4.4

**Comment by vico93** [comment]
Any updates?

**Comment by zenfyrdev** [comment]
Yes, I've looked into it. There are some really breaking changes. [But I'm a bit busy ATM](https://mstdn.social/@melontini/112440628438033625).

**Comment by zenfyrdev** [comment]
https://modrinth.com/mod/linkart/version/5.4.4-1.20.6-build.28

**Comment by vico93** [comment]
Thanks a lot!
