### ISSUE TITLE
Crash when spawning near a mineshaft (i think)

### ISSUE THREAD

**Issue by vico93** [constellation-mc/Linkart#33]
### What happened?

_Same deal with #32, no need to worry, just trying to figure out what need to be changed for 1.20.6._

Well, in resume, i created a new world, and while it was generating, it crashed. Looking through the logs, seems like it was because i spawned near a mineshaft and the culprit was a minecart with chest.

### Logs

https://gist.github.com/vico93/672608d9ae4a1f6d403e74c1d9abb3a0

### Version

5.4.4

**Comment by zenfyrdev** [comment]
Hi, I'm aware of those crashes. I haven't looked into it fully yet, but I'll try to, when I finish updating Andromeda's config system. All of this should be tracked on the old issue
