### ISSUE TITLE
Question about 1.21

### ISSUE THREAD

**Issue by Riyuukii** [constellation-mc/Linkart#39]
### What would you like to see added?

I'm just curious if this mod will be ported to 1.21 or not. ty in advance! ^^

**Comment by zenfyrdev** [comment]
Yes, but it's not the highest priority.

**Comment by Riyuukii** [comment]
> Yes, but it's not the highest priority.

alright! can't wait for the port ^^

**Comment by zenfyrdev** [comment]
This ended up being easier than I thought, so here it is: https://modrinth.com/mod/linkart/version/5.4.5-1.20.6-build.29

Everything should be working fine, as far as I'm aware.
