### ISSUE TITLE
Doesn't work on 1.18.2.

### ISSUE THREAD

**Issue by onyxromero** [constellation-mc/Linkart#4]
I found the fix though, all you have to do is just change version "1.17.x" to ">=1.17" in the fabric.mod.json file in order for the mod to run on versions 1.17-1.18.2.

**Comment by zenfyrdev** [comment]
Huh, it works fine on Quilt 1.18.2, but broken on Fabric...
Thanks for reporting! (Sorry for the late response, GitHub decided not to send me a notification)
