### ISSUE TITLE
Can we use chain from other mods?

### ISSUE THREAD

**Issue by ardissaps** [constellation-mc/Linkart#5]
Like Charm or other that add chain

**Comment by zenfyrdev** [comment]
Hi, not currently, but I do want to add tag support.

I'll try to add that soonish.

**Comment by ardissaps** [comment]
> Hi, not currently, but I do want to add tag support.
> 
> I'll try to add that soonish.

Thank you very much! (1.18.2) :p

**Comment by zenfyrdev** [comment]
Hey, I added tag support in the latest release.
You can now define custom linkers with `linkart:linker_items` tag.

By default, only vanilla chain is in, since if I add modded chains the tag might not load.
