### ISSUE TITLE
[Suggestion] Integrate features from Signals mod to Linkart

### ISSUE THREAD

**Issue by vico93** [constellation-mc/Linkart#9]
Okay, i think this one could sound very ambitous, but its actually the only thing left to make this mod a real alternative to TrainCarts native for Fabric.

Basically, [Signals](https://legacy.curseforge.com/minecraft/mc-mods/signals) ([GH](https://github.com/MineMaarten/Signals)) is an old mod for 1.12.2 that add signals block similar to OpenTTD/Factorio to the game, plus an routing system that would finally unleash a fully autonomous avenue to minecarts (in case of Linkart, combined minecarts).

Here is a review of how it worked originally on the mod:
https://www.youtube.com/watch?v=jAr_LvWhkQY

**Comment by vico93** [comment]
Any feedback about this idea?

**Comment by zenfyrdev** [comment]
Sorry, I'm a bit busy at the moment. This looks interesting and I'll look into it.
